// Bilingual case-study content. L(pt, en) → resolved by the portfolio DC.
const L = (pt, en) => ({ pt, en });
const I = (f) => 'assets/cases/c/' + f;

const LIGHT = { bg: '#ffffff', ink: '#1d1d1f', muted: '#6b6b70', panel: '#f4f4fa', border: '#e6e4ef', chipBorder: '#dcdae6', onAccent: '#ffffff' };
const DARK = { bg: '#06232c', ink: '#ffffff', muted: 'rgba(255,255,255,0.74)', panel: '#0c3440', border: 'rgba(255,255,255,0.14)', chipBorder: 'rgba(255,255,255,0.28)', onAccent: '#06232c' };

export const CASES = {
  olivia: {
    theme: { ...LIGHT, accent: '#7b6ee6', accentSoft: '#ece9fb' },
    blocks: [
      { t: 'hero', eyebrow: L('S1NC · Aplicativo mobile · App com IA', 'S1NC · Mobile application · AI app'), title: L('Assistente financeiro com IA', 'AI financial assistant'),
        chips: [L('UX Research', 'UX Research'), L('UI Design', 'UI Design'), L('Prototipação', 'Prototyping'), L('AI Design', 'AI Design'), L('Design System', 'Design System')],
        by: L('Jennifer — UX/UI Designer', 'Jennifer — UX/UI Designer'), right: L('6 semanas · 2026', '6 weeks · 2026'), img: I('ol-hero.jpg') },
      { t: 'split', side: 'right', img: I('ol-context.jpg'), eyebrow: L('Contexto', 'Context'),
        title: L('A informação financeira existia. Encontrá-la era o verdadeiro desafio.', 'Financial information existed. Finding it was the real challenge.'),
        body: [L('Hoje, quem usa o S1NC precisa cruzar manualmente extrato, categorias e limites só para responder a uma pergunta simples: "Quanto ainda posso gastar este mês?". Cada pergunta vira uma navegação por menus — e nem sempre a resposta fica clara no final.',
          'Today, anyone using S1NC has to manually cross-check statements, categories, and limits just to answer a simple question: "How much can I still spend this month?" Every question turns into navigating through menus — and the answer isn\'t always clear at the end.')] },
      { t: 'split', side: 'left', img: I('ol-goal.jpg'), eyebrow: L('Objetivo', 'Goal'),
        title: L('Transformar dúvidas financeiras do dia a dia em respostas imediatas, em linguagem natural.', 'Turn everyday financial questions into immediate answers, in natural language.'),
        body: [L('Desenhar um assistente conversacional dentro do S1NC capaz de responder perguntas sobre saldo, categorias e histórico de compras — sem exigir que o usuário navegue por relatórios para encontrar a resposta.',
          'Design a conversational assistant within S1NC capable of answering questions about balance, categories, and purchase history — without requiring the user to navigate through reports to find the answer.')] },
      { t: 'cards', cols: 2, eyebrow: L('Personas', 'Personas'), title: L('Quem vai conversar com a IA', 'Who will talk to the AI'),
        items: [
          { avatar: I('ol-marcela.jpg'), name: 'Marcela', meta: L('35 anos · Dona de casa · São Paulo', '35 years old · Homemaker · São Paulo'), quote: L('"Minha vida é ser mãe"', '"My life is being a mom"'),
            body: L('Casada, mãe de dois filhos e responsável por administrar as finanças da casa. Precisa de respostas rápidas no celular, sem navegar por várias telas.', 'Married, mother of two children, and responsible for managing the household finances. Needs quick answers on her phone, without navigating through multiple screens.'),
            fields: [{ k: L('Frustração', 'Frustration'), v: L('Não tenho respostas acessíveis e rápidas', 'I don\'t have accessible and quick answers') }, { k: L('O que ela precisa', 'What she needs'), v: L('Ter acesso às informações para tomar decisões financeiras em casa', 'To have access to information in order to make financial decisions at home') }],
            chips: ['WhatsApp', 'Instagram', 'YouTube'] },
          { avatar: I('ol-jorge.jpg'), name: 'Jorge', meta: L('25 anos · Motorista de Uber · Rio de Janeiro', '25 years old · Uber driver · Rio de Janeiro'), quote: L('"Amo viajar e estar com meus amigos"', '"I love traveling and being with my friends"'),
            body: L('Autônomo. Gosta de videogame. Tem dificuldade em controlar os próprios gastos e em decisões simples do dia a dia — como "posso comprar esse tênis este mês?".', 'Freelancer. Likes video games. Has trouble controlling his own spending and struggles with simple everyday decisions — like "can I afford these sneakers this month?"'),
            fields: [{ k: L('Frustração', 'Frustration'), v: L('Não tenho tempo de olhar várias telas.', 'I don\'t have time to look through multiple screens.') }, { k: L('O que ele precisa', 'What he needs'), v: L('Um lugar que mostre as respostas, para que ele possa tomar decisões.', 'A hub that shows him the answers, so he can make decisions.') }],
            chips: ['Cursor', 'Instagram', 'Claude'] }
        ] },
      { t: 'stats', eyebrow: L('Pesquisa & dados', 'Research & data'), title: L('O que a pesquisa mostrou', 'What the research showed'),
        items: [{ n: '60%', l: L('Disseram preferir extrair dados conversando', 'Said they prefer to extract data by talking (in a conversation)') }, { n: '30%', l: L('Já usam chat por voz em outros apps', 'Already use voice chat in other apps') }, { n: '25%', l: L('Usam o app mobile', 'Use the mobile app') }],
        note: L('Dados reais das entrevistas — consolidados a partir da pesquisa', 'Real data from the interviews — clarified based on research') },
      { t: 'panel', eyebrow: L('Solução', 'Solution'),
        title: L('Um chat dentro do S1NC que lê o extrato do usuário e dá respostas simples sobre quanto ele pode gastar, onde gastou e o que fazer a seguir — com chips de sugestão para perguntas comuns e respostas que viram um resumo visual quando faz sentido.',
          'A chat within S1NC that reads the user\'s statement and gives simple answers about how much they can spend, where they spent it, and what to do next — with suggestion chips for common questions, and answers that turn into a visual summary when it makes sense.'),
        imgs: [I('ol-sol-phone.jpg'), I('ol-sol-grad.jpg')] },
      { t: 'split', side: 'right', img: I('ol-hand.jpg'), eyebrow: L('IA no produto', 'AI in the product'), title: L('Uma conversa no lugar de três telas.', 'A conversation instead of three screens.'),
        label: L('Onde a IA entra', 'Where the AI comes in'),
        body: [L('Personalização e automação: a IA interpreta perguntas sobre orçamento, categorias e histórico de compras, e responde com base nos dados reais da conta do usuário.', 'Personalization and automation: the AI interprets questions about budget, categories, and purchase history, and responds based on the user\'s real account data.')],
        stepsLabel: L('Como funciona', 'How it works'),
        steps: [L('O usuário pergunta em linguagem natural, por texto ou voz.', 'The user asks in natural language, by text or voice.'), L('A IA interpreta a intenção e cruza com extrato, categorias e limites.', 'The AI interprets the intent and cross-references it with the statement, categories, and limits.'), L('A resposta vem em texto, com um resumo visual quando ajuda a entender.', 'The answer comes in text, with a visual summary when it helps with understanding.'), L('O usuário confirma, aprofunda ou faz uma nova pergunta.', 'The user confirms, digs deeper, or asks a new question.')] },
      { t: 'flow', eyebrow: L('Fluxo de navegação', 'Navigation flow'), title: L('Da Home até a resposta', 'From Home to the answer'),
        main: [L('Home', 'Home'), L('Ícone da IA', 'AI icon'), L('Chat com IA', 'AI chat'), L('Resposta + resumo visual', 'Answer + visual summary')], branches: [L('Detalhe da categoria', 'Category detail'), L('Nova pergunta', 'New question')] },
      { t: 'heading', eyebrow: L('Funcionalidades', 'Features'), title: L('Onde a conversa faz diferença', 'Where the conversation makes a difference') },
      { t: 'split', side: 'right', img: I('ol-voice.jpg'), compact: true, title: L('Consulta por texto ou voz', 'Text or voice query'),
        body: [L('O usuário pergunta do jeito que falaria naturalmente — "quanto ainda tenho para alimentação?" — e recebe a resposta sem precisar saber onde essa informação fica no app (o que promove mais acessibilidade para pessoas com deficiência visual).', 'The user asks the way they\'d naturally speak — "how much do I have left for food?" — and gets the answer without needing to know where that information lives in the app (which promotes greater accessibility for visually impaired users).')] },
      { t: 'split', side: 'left', img: I('ol-history.jpg'), compact: true, title: L('Histórico de conversas', 'Conversation history'),
        body: [L('O usuário pode iniciar uma conversa e voltar a ela de forma rápida e fácil, caso queira revisitar um diálogo com a IA.', 'The user can start a conversation and then access it again quickly and easily, if they want to revisit a conversation with the AI.')] },
      { t: 'split', side: 'right', img: I('ol-alerts.jpg'), compact: true, title: L('Alertas proativos de gasto', 'Proactive spending alerts'),
        body: [L('A IA avisa antes que o limite de uma categoria seja ultrapassado, para garantir que as funcionalidades do app façam diferença real na vida financeira do usuário.', 'The AI warns before a category limit is exceeded, to ensure the app\'s features can make a real difference in the user\'s financial life.')] },
      { t: 'image', eyebrow: L('Guia de estilo', 'Style guide'), title: L('Sistema visual', 'Visual system'), src: I('ol-style.jpg') },
      { t: 'gantt', eyebrow: L('Cronograma do projeto', 'Project timeline'), title: L('6 semanas, do zero à UI final', '6 weeks, from zero to final UI'),
        rows: [
          { label: L('Pesquisa', 'Research'), bar: L('Pesquisa — 1 semana', 'Research — 1 week'), start: 0, width: 26, strong: true },
          { label: L('Ideação', 'Ideation'), bar: L('Ideação — 1 semana', 'Ideation — 1 week'), start: 0, width: 38, strong: false },
          { label: L('Wireframes', 'Wireframes'), bar: L('Wireframes — 1 semana', 'Wireframes — 1 week'), start: 12, width: 39, strong: true },
          { label: L('Prototipação', 'Prototyping'), bar: L('Prototipação — 1 semana', 'Prototyping — 1 week'), start: 18, width: 28, strong: false },
          { label: L('Testes', 'Testing'), bar: L('Teste de usabilidade — 1 semana', 'Usability testing — 1 week'), start: 34, width: 40, strong: true },
          { label: L('Versão final', 'Final version'), bar: L('Versão final — 1 semana', 'Final version — 1 week'), start: 46, width: 54, strong: false }
        ] },
      { t: 'end', text: L('S1NC · Chat com IA', 'S1NC · AI chat') }
    ]
  },

  appWeb: {
    theme: { ...LIGHT, bg: '#f8f8f7', ink: '#1a1a1a', muted: '#6b6b6b', panel: '#efeeeb', border: '#e5e3df', chipBorder: '#d8d6d1', accent: '#fe3b5d', accentSoft: '#ffe3e8' },
    blocks: [
      { t: 'hero', eyebrow: L('Chat Support · Web app SaaS B2B', 'Chat Support · B2B SaaS web app'), title: L('Chat Support', 'Chat Support'),
        chips: [L('Product Design', 'Product Design'), L('UX Research', 'UX Research'), L('UI Design', 'UI Design'), L('Dashboard de métricas', 'Metrics Dashboard')],
        by: L('Design & Estratégia: Jennifer', 'Design & Strategy: Jennifer'), right: L('6 semanas · 2026', '6 weeks · 2026'), img: I('cs-hero.jpg') },
      { t: 'split', eyebrow: L('O problema', 'The problem'), title: L('O custo real de operar o suporte sem visibilidade de status.', 'The real cost of running support with no visibility into status.'),
        body: [L('Com canais espalhados — e-mail, WhatsApp, planilhas — o agente reconstrói o contexto a cada ticket, e o gestor decide no feeling, não com dados. Na prática: tempo de atendimento maior, qualidade que depende de quem atende e nenhuma métrica confiável para justificar contratações ou mudanças de processo. Isso não é um problema de suporte — é uma decisão de negócio sendo tomada sem uma ferramenta real para sustentá-la.',
          'Across scattered channels — email, WhatsApp, spreadsheets — the agent rebuilds context for every ticket, and the manager decides based on gut feeling, not data. In practice: longer handling times, service quality that depends on the agent, and no reliable metric to justify hiring or process changes. This isn\'t a support problem — it\'s a business decision being made without a real tool to support it.')] },
      { t: 'panel', eyebrow: L('Nossa solução', 'Our solution'), title: L('Uma inbox única.', 'One single inbox.'), big: true,
        body: [L('Uma tela de inbox de suporte que reúne todas as conversas em uma só visão, com filtros por prioridade (alta/baixa), tempo de espera (maior/menor) e status (aberto, pendente, escalado). Cada conversa mostra um resumo curto, para o agente entender o contexto rápido antes de abrir o ticket; ao clicar, abre a conversa completa junto com o perfil do cliente, unindo histórico e atendimento em um único fluxo. O objetivo é reduzir o tempo de triagem e padronizar como os tickets são priorizados, em vez de deixar isso a critério de cada agente.',
          'A support inbox screen that brings every conversation into one view, with filters by priority (high/low), wait time (longest/shortest) and status (open, pending, escalated). Each conversation shows a short summary, so the agent can understand the context fast before opening the ticket; clicking it opens the full conversation together with the customer profile, joining history and support into a single flow. The goal is to cut triage time and standardize how tickets get prioritized, instead of leaving it to each agent\'s own judgment.')],
        note: L('Teoria por trás: teoria da carga cognitiva de John Sweller — interfaces mal desenhadas desperdiçam a capacidade limitada de processamento com coisas que não são o trabalho em si.', 'Theory behind it: John Sweller\'s cognitive load theory — poorly designed interfaces waste limited processing capacity on things that aren\'t the actual work.'),
        imgs: [I('cs-solution.jpg')] },
      { t: 'cards', cols: 2, eyebrow: L('Personas', 'Personas'), title: L('Quem usa o produto', 'Who uses the product'),
        items: [
          { initials: ' ', name: L('Agente de suporte', 'Support agent'), body: L('Atende tickets todos os dias. Precisa ver prioridade, histórico e contexto do cliente sem trocar de tela nem depender da memória de casos anteriores.', 'Handles tickets every day. Needs to see priority, history and customer context without switching screens or relying on memory from past cases.') },
          { initials: ' ', name: L('Cliente final', 'End customer'), body: L('Abre o ticket. Espera uma resposta rápida e não quer repetir o problema a cada novo contato — quer sentir que alguém já sabe quem ele é.', 'Opens the ticket. Expects a fast reply and doesn\'t want to repeat the problem on every new contact — wants to feel like someone already knows who they are.') }
        ] },
      { t: 'split', eyebrow: L('Pesquisa & dados', 'Research & data'), title: L('Dados reais no lugar do achismo na gestão do time.', 'Real data replacing guesswork in team management.'),
        body: [L('Volume diário, tempo médio de resposta e carga por agente, tudo no mesmo painel — a mesma lógica de descoberta contínua de que Teresa Torres fala: decisões de produto e operação apoiadas em evidência real de uso, não na opinião do gestor mais experiente da sala.', 'Daily volume, average response time and workload per agent, all on the same panel — the same continuous-discovery logic Teresa Torres talks about: product and operations decisions backed by real usage evidence, not by the opinion of the most experienced manager in the room.')],
        wide: I('cs-workload.jpg'), note: L('Referência: Teresa Torres, Opportunity Solution Trees — Product Talk.', 'Reference: Teresa Torres, Opportunity Solution Trees — Product Talk.') },
      { t: 'split', side: 'right', eyebrow: L('IA no produto — uma proposta de produto, ainda não construída', 'AI in the product — a product proposal, not a built feature yet'), title: L('Priorização assistida por IA para a fila de tickets.', 'AI-assisted prioritization for the ticket queue.'),
        body: [L('A dor: gestores e agentes ainda decidem a prioridade "no feeling". A ideia: um assistente que lê o contexto do ticket (histórico do cliente, palavras-chave, tempo na fila) e sugere uma prioridade e uma primeira resposta — o agente sempre confirma antes de enviar. Fluxo: ticket chega → IA lê contexto e histórico → IA sugere prioridade e rascunho de resposta → agente revisa e confirma.',
          'The pain point: managers and agents still decide priority "by feel". The idea: an assistant that reads the ticket\'s context (customer history, keywords, time in queue) and suggests a priority and a first reply — the agent always confirms before sending. Flow: ticket comes in → AI reads context and history → AI suggests priority and a draft reply → agent reviews and confirms.')],
        card: { label: L('Sugestão da IA', 'AI suggestion'), text: L('O ticket #1082 parece crítico: cliente Enterprise, 3ª tentativa em 24h. Sugiro escalar e usar a resposta abaixo.', 'Ticket #1082 looks critical: Enterprise customer, 3rd attempt in 24h. I suggest escalating and using the reply below.'),
          buttons: [{ label: L('Escalar', 'Escalate'), bg: '#fe3b5d' }, { label: L('Usar rascunho', 'Use draft'), bg: '#5c97f8' }],
          quote: L('"Oi, vi que a importação do seu pagamento falhou de novo — já enviei para o time técnico com prioridade alta."', '"Hi, I can see your payment import failed again — I\'ve already sent it to the technical team with high priority."') } },
      { t: 'split', side: 'left', img: I('cs-inbox.jpg'), imgW: 420, eyebrow: L('Decisão de UX', 'UX decision'), title: L('Uma fila priorizada por status, sempre visível.', 'A queue prioritized by status, always visible.'),
        body: [L('O agente nunca precisa perguntar "o que está acontecendo com esse ticket" — ele simplesmente vê. A fila elimina a triagem manual: o próximo ticket é escolhido olhando, não procurando.', 'The agent never has to ask "what\'s going on with this ticket" — they just see it. The queue removes manual triage: the next ticket is chosen by looking, not by searching.')],
        note: L('Heurística 1 — Visibilidade do status do sistema. NN/g — Visibility of System Status.', 'Heuristic 1 — Visibility of system status. NN/g — Visibility of System Status.') },
      { t: 'split', side: 'right', img: I('cs-history.jpg'), imgW: 420, eyebrow: L('Decisão de UX', 'UX decision'), title: L('Histórico e status sempre à vista, nunca reconstruídos do zero.', 'History and status always in view, never rebuilt from scratch.'),
        body: [L('Reconhecer custa menos que lembrar. Um painel do cliente, com histórico e status sempre exibidos na conversa, tira a carga da memória do agente e a coloca na interface, onde custa menos processar.', 'Recognizing is cheaper than recalling. A customer panel, with history and status always shown in the conversation, takes the load off the agent\'s memory and puts it on the interface instead, where it costs less to process.')],
        note: L('Heurística 6 — Reconhecer em vez de lembrar. NN/g — Memory Recognition and Recall in User Interfaces.', 'Heuristic 6 — Recognition rather than recall. NN/g — Memory Recognition and Recall in User Interfaces.') },
      { t: 'split', side: 'left', img: I('cs-clients.jpg'), eyebrow: L('Decisão de UX', 'UX decision'), title: L('Histórico do cliente sem garimpar telas.', 'Customer history without digging through screens.'),
        body: [L('Trocar de tela custa tempo e quebra a concentração. A lista de clientes está a um clique, com número de atendimentos e último contato visíveis — o agente nunca precisa sair da fila para entender quem está do outro lado.', 'Switching screens costs time and breaks concentration. The customer list is one click away, with ticket count and last contact visible — the agent never has to leave the queue to understand who\'s on the other side.')],
        note: L('Heurística 7 — Flexibilidade e eficiência de uso. NN/g — 10 Usability Heuristics for User Interface Design.', 'Heuristic 7 — Flexibility and efficiency of use. NN/g — 10 Usability Heuristics for User Interface Design.') },
      { t: 'split', side: 'right', img: I('cs-dashboard.jpg'), eyebrow: L('Decisão de UX', 'UX decision'), title: L('As métricas do dashboard são as que o gestor realmente usa.', 'The dashboard\'s metrics are the metrics the manager actually uses.'),
        body: [L('Volume, tempo de resposta e carga por agente aparecem exatamente do jeito que o gestor já pensa sobre eles — sem tradução técnica no meio. O dashboard fala a mesma língua da decisão de negócio.', 'Volume, response time and workload per agent show up exactly the way the manager already thinks about them — with no technical translation in between. The dashboard speaks the same language as the business decision.')],
        note: L('Heurística 8 — Correspondência entre o sistema e o mundo real. NN/g — 10 Usability Heuristics for User Interface Design.', 'Heuristic 8 — Match between system and the real world. NN/g — 10 Usability Heuristics for User Interface Design.') },
      { t: 'weeks', eyebrow: L('Processo', 'Process'), title: L('Cronograma do projeto', 'Project timeline'), pill: L('1 semana', '1 week'),
        rows: [L('Pesquisa', 'Research'), L('Ideação', 'Ideation'), L('Wireframes', 'Wireframes'), L('Prototipação', 'Prototyping'), L('Testes', 'Testing'), L('Entrega', 'Delivery')] },
      { t: 'palette', eyebrow: L('Guia de estilo', 'Style guide'), title: L('Paleta de cores funcional por status', 'Functional color palette by status'),
        body: L('Cores usadas em badges, filtros e barras do dashboard — tiradas direto da interface real do produto, cada status de ticket mantém uma cor fixa, reconhecível em todas as telas.', 'Colors used for badges, filters and dashboard bars — pulled directly from the real product interface, each ticket status keeps a fixed color, recognizable on every screen.'),
        items: [{ label: L('Aberto', 'Open'), hex: '#5C97F8' }, { label: L('Pendente', 'Pending'), hex: '#F5A011' }, { label: L('Escalado', 'Escalated'), hex: '#FE3B5D' }, { label: L('Resolvido', 'Resolved'), hex: '#4FCCA2' }],
        specimen: 'AaBbCc 0123456789', note: L('Manrope — títulos em peso médio · Manrope — texto corrido em peso regular.', 'Manrope — headings in medium weight · Manrope — body text in regular weight.') },
      { t: 'points', eyebrow: L('Resultados & aprendizados', 'Results & learnings'), title: L('Menos tempo perdido, decisões mais seguras, suporte mais claro.', 'Less time wasted, safer decisions, clearer support.'),
        items: [
          { title: L('Tempo de resposta menor', 'Faster response time'), body: L('Uma fila priorizada por status elimina a triagem manual — o agente escolhe o próximo ticket olhando, não procurando.', 'A queue prioritized by status removes manual triage — the agent picks the next ticket by looking, not by searching.') },
          { title: L('Atendimento consistente entre agentes', 'Consistent service across agents'), body: L('Status, histórico e perfil compartilhados eliminam a dependência do conhecimento individual — a qualidade não depende mais de quem responde.', 'Shared status, history and profile remove the dependency on individual knowledge — quality no longer depends on who answers.') },
          { title: L('Decisões de gestão mais seguras', 'Safer management decisions'), body: L('Volume, tempo de resposta e carga por agente, antes invisíveis, viram um indicador de gestão apoiado em dados, não no feeling.', 'Volume, response time and workload per agent, once invisible, become a management indicator backed by data, not by gut feeling.') }
        ] },
      { t: 'refs', eyebrow: L('Referências', 'References'), title: L('Em que essas decisões se apoiam', 'What these decisions are based on'),
        items: [{ src: 'Nielsen Norman Group', title: '10 Usability Heuristics for User Interface Design' }, { src: 'Nielsen Norman Group', title: 'Visibility of System Status' }, { src: 'Nielsen Norman Group', title: 'Memory Recognition and Recall in User Interfaces' }, { src: 'Teresa Torres — Product Talk', title: 'Opportunity Solution Trees' }, { src: 'McKinsey Design', title: 'The business value of design' }] }
    ]
  },

  pesquisa: {
    theme: { ...LIGHT, ink: '#0b1f26', muted: '#5f6b73', panel: '#f3f4f4', border: '#e3e6e8', chipBorder: '#d9dde0', accent: '#3f9c96', accentSoft: '#dff1ef' },
    blocks: [
      { t: 'hero', eyebrow: L('S1NC · Aplicativo mobile · App com IA', 'S1NC · Mobile application · AI app'), title: L('Teste A/B — Usabilidade (Extrato)', 'A/B test — Usability (Statement)'),
        chips: [L('UX Research', 'UX Research'), L('Teste A/B', 'A/B Test'), L('Pesquisa', 'Research')], by: L('Jennifer — UX/UI Designer', 'Jennifer — UX/UI Designer'), right: L('1 semana · 2026', '1 week · 2026'), img: I('ps-hero.jpg') },
      { t: 'split', side: 'right', eyebrow: L('Contexto', 'Context'), title: L('O extrato existia. Entendê-lo era o verdadeiro desafio.', 'The statement existed. Understanding it was the real challenge.'),
        body: [L('O S1NC mistura transações da conta corrente com gastos do cartão de crédito em uma única visão de fluxo de caixa — criando cinco distorções estruturais que confundem o usuário.', 'S1NC mixes checking account transactions with credit card spending into a single cash flow view — creating five structural distortions that confuse the user.')],
        list: [L('Saldo irreal por causa da contabilidade por competência', 'Unrealistic balance due to accrual-based accounting'), L('Contagem duplicada dos gastos no cartão de crédito', 'Double counting of credit card spending'), L('Falta de visibilidade do que será pago no mês atual', 'Lack of visibility into what will be paid in the current month'), L('Nenhuma separação entre conta e cartão', 'No separation between account and card'), L('Tela do cartão com baixo valor percebido', 'Card screen with low perceived value')] },
      { t: 'split', side: 'left', img: I('ps-goal.jpg'), eyebrow: L('Objetivo', 'Goal'), title: L('Três visões, três respostas claras.', 'Three views, three clear answers.'),
        body: [L('Separar saldo da conta, fatura do cartão e visão consolidada de gastos — cada tela respondendo a uma pergunta específica, sem misturar lógicas financeiras diferentes.', 'Separate account balance, card invoice, and consolidated spending view — each screen answering a specific question, without mixing different financial logics.')] },
      { t: 'cards', cols: 3, eyebrow: L('Personas', 'Personas'), title: L('Quem sente os problemas', 'Who feels the problems'), sub: L('Qual modelo de exibição de transações você acha mais fácil de entender?', 'Which transaction display model do you find easiest to understand?'),
        items: [
          { initials: 'CW', name: L('Consultor W1', 'W1 Consultant'), tag: L('Principal dor', 'Main pain point'), body: L('Precisa explicar as distorções do app em reuniões com clientes; perde credibilidade.', 'Needs to explain the app\'s distortions in meetings with clients; loses credibility.') },
          { initials: 'UF', name: L('Usuário Free', 'Free User'), tag: L('Principal dor', 'Main pain point'), body: L('A interface confusa obriga a ocultar transações manualmente.', 'Confusing interface forces manual hiding of transactions.') },
          { initials: 'UP', name: L('Usuário Premium', 'Premium User'), tag: L('Principal dor', 'Main pain point'), body: L('Se confunde com gastos duplicados causados por bugs do Open Finance; não sabe quanto vai ser a fatura.', 'Confuses duplicated spending caused by Open Finance bugs; doesn\'t know how much the invoice will be.') }
        ] },
      { t: 'stats', eyebrow: L('Pesquisa & teste A/B', 'Research & A/B test'), title: L('O que a pesquisa mostrou', 'What the research showed'),
        items: [{ n: '41', l: L('Respondentes — Consultores', 'Respondents — Consultants') }, { n: '7', l: L('Perguntas (5 fechadas + 2 abertas)', 'Questions (5 closed-ended + 2 open-ended)') }, { n: L('10–16 jun', 'Jun 10–16'), l: L('Período de coleta da pesquisa', 'Research collection period') }] },
      { t: 'panel', eyebrow: L('Solução', 'Solution'),
        title: L('Três telas: Conta, Cartão de Crédito e Gastos Mensais — substituindo o extrato único. Gastos Mensais resolve a falta de visibilidade do fluxo de caixa real, permitindo ao usuário escolher entre regime de competência (data da compra) ou de caixa (vencimento da fatura).',
          'Three screens: Account, Credit Card, and Monthly Spending — replacing the single statement. Monthly Spending solves the lack of visibility into actual cash flow, letting the user choose between accrual basis (purchase date) or cash basis (invoice due date).') },
      { t: 'image', eyebrow: L('Resultado & teste A/B', 'Result & A/B test'), title: L('Onde os dados decidiram o DESIGN', 'Where the data decided the DESIGN'), sub: L('Qual modelo de exibição de transações você acha mais fácil de entender?', 'Which transaction display model do you find easiest to understand?'), src: I('ps-ab.jpg') },
      { t: 'split', side: 'right', eyebrow: L('Pergunta 1', 'Question 1'), title: L('Navegação entre visões', 'Navigation between views'),
        body: [L('49% escolheram a Opção B — um único componente com as três visões garante que o usuário esteja sempre ciente das três visões disponíveis.', '49% chose Option B — a single component with three views ensures the user is always aware of the three views available.')],
        bars: [{ label: 'B', value: 20, pct: 100, win: true }, { label: 'C', value: 11, pct: 55 }, { label: 'A', value: 10, pct: 50 }] },
      { t: 'split', side: 'left', eyebrow: L('Pergunta 2', 'Question 2'), title: L('Nome da tela consolidada', 'Name of the consolidated screen'),
        body: [L('"Gastos Mensais" combina a clareza de "Gastos do Mês" com a precisão temporal de "Mensal", evitando a ambiguidade de "Visão Geral".', '"Gastos Mensais" (Monthly Spending) combines the clarity of "Gastos do Mês" with the time precision of "Mensal", avoiding the ambiguity of "Visão Geral" (Overview).')],
        bars: [{ label: 'Gastos Mensais', pct: 100, win: true, winLabel: L('Vencedor', 'Winner') }, { label: 'Gastos do Mês', pct: 80 }, { label: 'Visão Geral', pct: 60 }], barsStacked: true },
      { t: 'twoLists', eyebrow: L('Decisões', 'Decisions'), title: L('Do voto à decisão de design', 'From the vote to the design decision'),
        cols: [
          { label: L('Sobre o problema', 'About the problem'), color: '#e0644a', items: [L('Cinco distorções estruturais no extrato único', 'Five structural distortions in the single statement'), L('Gastos do cartão de crédito duplicados nos relatórios', 'Duplicated credit card spending in reports'), L('Nenhuma visão clara do que ainda será cobrado na fatura', 'No clear view of what will still be charged to the invoice')] },
          { label: L('Visão geral da solução', 'Solution overview'), color: '#1fa37a', items: [L('Componente único com as três visões (Opção B)', 'Single component with the three views (Option B)'), L('Visão padrão ao abrir o app: Gastos Mensais', 'Default view when opening the app: Monthly Spending'), L('Número como foco principal, gráfico como apoio', 'Number as the main focus, chart as support')] }
        ] },
      { t: 'panel', eyebrow: L('Solução', 'Solution'), quote: L('"Eu não precisaria mais ficar escondendo pagamentos de fatura."', '"I wouldn\'t have to keep hiding invoice payments anymore."'), cite: L('Participante da pesquisa · Consultor W1', 'Research participant · W1 consultant') },
      { t: 'learnings', eyebrow: L('Aprendizados', 'Learnings'), title: L('O que aprendemos até aqui', 'What we\'ve learned so far'),
        items: [L('Usuários preferem uma visão completa: em Gastos Mensais, todos entenderam o número total como o saldo — não como a soma de conta + cartão.', 'Users prefer a complete view: in Monthly Spending, everyone saw the total number as the balance — not as the sum of account + card.'), L('Consultores preferem ver números a gráficos.', 'Consultants prefer viewing numbers rather than charts.'), L('Usuários preferem uma visão separada para cada coisa, mais limpa, em vez de várias informações pequenas em uma única tela.', 'Users prefer a separate view for each thing, cleaner, rather than several small pieces of information on a single screen.')] }
    ]
  },

  wcag: {
    theme: { ...DARK, accent: '#2fd0bd', accentSoft: 'rgba(47,208,189,0.16)' },
    blocks: [
      { t: 'hero', eyebrow: L('Estudo de caso · W1 Consultoria', 'Case study · W1 Consultoria'), title: L('App de Gestão Financeira', 'Financial Management App'),
        chips: [L('Auditoria de UX', 'UX Audit'), L('Heurísticas de Nielsen', 'Nielsen Heuristics'), L('Acessibilidade', 'Accessibility'), L('Benchmarking', 'Benchmarking')],
        by: L('por W1 Consultoria', 'by W1 Consultoria'), right: L('S1NC · 2025', 'S1NC · 2025'), img: I('wc-cover.jpg'), imgW: 640 },
      { t: 'audit', title: L('Tela inicial', 'Home screen'), img: I('wc-home.jpg'),
        pairs: [{ opp: L('Oportunidade de melhoria', 'Opportunity for improvement'), oppBody: L('A posição da função "Não ver mais isso" facilita que o usuário a acione sem querer ao tentar sair da tela, já que ela fica muito próxima do Home Indicator. Segundo as Heurísticas de Nielsen — especificamente a Heurística 5 (Prevenção de erros) — esse posicionamento não é ideal, porque a proximidade com o Home Indicator aumenta a chance de um toque errado. Isso pode causar frustração desnecessária e afetar a fluidez da experiência.', 'The position of the "Don\'t show this again" feature makes it easy for the user to trigger it by accident when trying to leave that screen, since it sits too close to the Home Indicator. According to Nielsen\'s Heuristics — specifically Heuristic 5 (Error Prevention) — this placement is not ideal, because being so close to the Home Indicator increases the chance of a wrong tap. This can cause unnecessary frustration and affect how smooth the experience feels.'),
          sug: L('Sugestão', 'Suggestion'), sugBody: L('Uma boa solução seria subir os botões "Começar" e "Cancelar", aproximando-os da opção "Não ver mais isso" e mantendo-os centralizados. Isso evitaria frustrações desnecessárias e criaria uma experiência mais fluida, seguindo a heurística de Nielsen sobre prevenção de erros.', 'A good solution would be to move the "Start" and "Cancel" buttons higher up, closer to the "Don\'t show this again" option, keeping them centered. This would prevent unnecessary frustration and create a smoother experience, following Nielsen\'s Heuristic on error prevention.') }] },
      { t: 'audit', title: L('Extrato', 'Statement'), img: I('wc-statement.jpg'),
        pairs: [
          { opp: L('Oportunidade — saldo visível', 'Opportunity — visible balance'), oppBody: L('O saldo da conta fica em uma área difícil de alcançar em termos de usabilidade mobile, especialmente para canhotos. Algumas informações devem mesmo ficar no topo, mas, para algo consultado todos os dias, esse não é o melhor lugar. Isso vai contra o estudo de Thumb Zone, que recomenda manter botões e menus ao alcance fácil do polegar.', 'Showing the account balance is hard to reach in terms of mobile usability, especially for left-handed users. Some information does belong at the top, but for something checked every day, this isn\'t the best placement. This goes against the Thumb Zone study, which recommends keeping buttons and menus within easy reach.'),
            sug: L('Sugestão — saldo visível', 'Suggestion — visible balance'), sugBody: L('Uma boa solução seria movê-lo mais para baixo na tela, ao alcance fácil tanto de destros quanto de canhotos, sem exigir um esforço extra que prejudique a usabilidade.', 'A good solution would be to move it further down the screen, so it\'s within easy reach for both right- and left-handed users, without asking them to make an extra effort that could hurt usability.') },
          { opp: L('Oportunidade — indicador de entrada/saída', 'Opportunity — income/expense indicator'), oppBody: L('O componente de entradas/saídas usa uma pequena seta para cada movimentação, mas elas são difíceis de distinguir num relance — uma inconsistência com a Heurística 1 de Nielsen (visibilidade do status do sistema). O usuário deveria ler a informação rapidamente, sem esforço extra. Cores distintas deixariam a interface mais fácil de entender.', 'The income/expense component uses a small arrow for each movement, but they\'re hard to tell apart at a glance — an inconsistency with Nielsen\'s Heuristic 1 (visibility of system status). Users should read information quickly, without extra effort. Distinct colors would make the interface easier to understand.'),
            sug: L('Sugestão — indicador de entrada/saída', 'Suggestion — income/expense indicator'), sugBody: L('Diferenciar as setas por cor ajudaria, seguindo a Heurística 1. Entradas poderiam aparecer em azul e saídas em vermelho, para que o usuário identifique as movimentações num relance, sem leitura extra, deixando a navegação mais clara.', 'Color-coding the arrows would help, following Heuristic 1. Income could be shown in blue and expenses in red, so users spot financial movements at a glance without extra reading, making navigation clearer.') }
        ] },
      { t: 'audit', title: L('Planejamento', 'Planning'), img: I('wc-plan1.jpg'),
        pairs: [{ opp: L('Oportunidade — adicionar um plano', 'Opportunity — add a plan'), oppBody: L('Na tela de Planejamento, não fica claro onde o usuário pode adicionar um novo plano. Cada categoria — Entrada, Investimento, Gasto Fixo e Variável — tem uma pequena seta que supostamente leva a outro lugar. Pela Heurística 4 de Nielsen (consistência e padrões), "Adicionar plano" deveria seguir o padrão de "Adicionar objetivo" e "Adicionar transação". A Heurística 6 também diz que o usuário deve reconhecer em vez de lembrar — a falta de padrão aqui pode quebrar o fluxo entre telas e, em alguns casos, levar à frustração e ao abandono do app.', 'On the Planning screen, it isn\'t clear where the user can add a new plan. Each category — Income, Investment, Fixed and Variable Expense — has a small arrow that presumably leads elsewhere. Based on Nielsen\'s Heuristic 4 (consistency and standards), "Add Plan" should match the pattern of "Add Goal" and "Add Transaction." Heuristic 6 also states that users should recognize rather than recall — the missing pattern here can break the flow between screens and, in some cases, lead to frustration and app abandonment.'),
          sug: L('Sugestão — adicionar um plano', 'Suggestion — add a plan'), sugBody: L('Padronizar os botões — "Adicionar plano", "Adicionar objetivo" e "Adicionar transação" — deixaria o app mais intuitivo, ajudando o usuário a reconhecer ações em vez de lembrá-las, conforme a Heurística 6. A consistência (Heurística 4) também ajudaria o usuário a entender rapidamente como interagir com cada elemento, reduzindo o esforço cognitivo. Para o time, unificar esses padrões reduziria o custo de desenvolvimento e manutenção e aumentaria a satisfação.', 'Standardizing the buttons — "Add Plan," "Add Goal" and "Add Transaction" — would make the app more intuitive, helping users recognize actions instead of recalling them, per Heuristic 6. Consistency (Heuristic 4) would also help users quickly understand how to interact with each element, reducing cognitive effort. For the team, unifying these patterns would lower development and maintenance cost while improving satisfaction.') }] },
      { t: 'audit', title: L('Planejamento', 'Planning'), img: I('wc-plan2.jpg'),
        pairs: [{ opp: L('Oportunidade — componente de entradas/saídas', 'Opportunity — income/expense component'), oppBody: L('O componente de gastos planejados/não planejados usa um layout diferente do equivalente na página de Extrato, embora os dois tenham a mesma função. Isso conflita com a Heurística 4 de Nielsen e ainda custa tempo ao time de desenvolvimento para construir e manter duas abordagens. A Heurística 6 agrava o problema: sem um padrão, a navegação fica menos intuitiva.', 'The planned/unplanned expenses component uses a different layout than the equivalent one on the Statement page, even though both serve the same purpose. This conflicts with Nielsen\'s Heuristic 4. It also costs the dev team time to build and maintain two approaches. Heuristic 6 makes this worse: without a pattern, navigation feels less intuitive.'),
          sug: L('Sugestão — componente de entradas/saídas', 'Suggestion — income/expense component'), sugBody: L('Alinhar esse componente ao layout da página de Extrato deixaria a navegação mais intuitiva, conforme a Heurística 4. Aplicando a Heurística 6, padronizá-lo tornaria o app mais fácil de usar. Para o time, componentes reutilizáveis e consistentes reduzem a complexidade de construção e manutenção, otimizando tempo e custo de desenvolvimento.', 'Aligning this component with the Statement page\'s layout would make navigation more intuitive, per Heuristic 4. Applying Heuristic 6, standardizing it would make the app easier to use. For the team, reusable, consistent components reduce build and maintenance complexity, optimizing development time and cost.') }] },
      { t: 'table', title: L('Benchmarking', 'Benchmarking'), legend: L('✓ disponível · $ recurso pago', '✓ available · $ paid feature'),
        head: ['Mobills', 'Organizze', 'Minhas Economias', 'WalletApp'],
        rows: [
          { label: L('Criar categoria', 'Create category'), cells: ['✓', '✓', '✓', '✓'] }, { label: L('Criar tags', 'Create tags'), cells: ['$', '✓', '✓', '✓'] },
          { label: L('Modo escuro', 'Dark mode'), cells: ['✓', '✓', '✓', ''] }, { label: L('Entrada/saída fixa', 'Fixed income/expense'), cells: ['✓', '✓', '✓', '✓'] },
          { label: L('Transação recorrente', 'Recurring transaction'), cells: ['✓', '✓', '✓', ''] }, { label: L('Vincular ao cartão', 'Link to card'), cells: ['$', '', '$', '$'] },
          { label: L('Salvar e continuar', 'Save and continue'), cells: ['✓', '✓', '✓', '✓'] }, { label: L('Definir um plano', 'Set a plan'), cells: ['$', '', '✓', '✓'] },
          { label: L('Criar subcategoria', 'Create subcategory'), cells: ['$', '✓', '✓', '✓'] }, { label: L('Importação bancária', 'Bank import'), cells: ['✓', '', '✓', '✓'] },
          { label: L('Exportar relatórios', 'Export reports'), cells: ['$', '', '$', ''] }, { label: L('Anexos nos lançamentos', 'Attachments on entries'), cells: ['✓', '✓', '✓', '✓'] },
          { label: L('Fatura do cartão com início e vencimento', 'Add card statement with start & due dates'), cells: ['✓', '✓', '✓', ''] }, { label: L('Escolher moeda', 'Choose currency'), cells: ['✓', '', '✓', '✓'] },
          { label: L('Lançar entrada/saída ainda não paga ou recebida', 'Log income/expense not yet paid or received'), cells: ['✓', '✓', '✓', '✓'] }, { label: L('Modo viagem', 'Travel mode'), cells: ['$', '', '✓', ''] }
        ] },
      { t: 'refs', title: L('Fontes', 'Sources'), items: [{ src: L('Referência', 'Reference'), title: L('W1App – Solução Financeira — página na App Store da Apple (categoria Finanças, desenvolvido pela W1)', 'W1App – Financial Solution — Apple App Store listing (Finance category, developed by W1)') }] }
    ]
  },

  mapa: {
    theme: { ...DARK, accent: '#b4f000', accentSoft: 'rgba(180,240,0,0.14)' },
    blocks: [
      { t: 'hero', eyebrow: L('Análise de UX · Clarity', 'UX analysis · Clarity'), title: L('Análise de UX — Mapa de calor', 'UX Analysis — Heat Mapping'),
        chips: [L('Mapa de calor', 'Heatmap'), L('Gravações de sessão', 'Session recordings'), L('Heurísticas de Nielsen', 'Nielsen Heuristics')],
        by: L('Um clique errado custa mais que um erro de código — custa confiança.', 'A wrong click costs more than a coding mistake — it costs trust.'), right: L('Jennifer Paiva — UX UI', 'Jennifer Paiva — UX UI'), img: I('mc-cover.jpg') },
      { t: 'split', eyebrow: L('Metodologia e fundamento', 'Methodology and foundation'), title: L('O desafio estratégico', 'The strategic challenge'),
        body: [L('Embora a landing page tenha bom desempenho e comunique com clareza, o fluxo de compra ainda tem pontos de atrito significativos. Rage clicks e uma taxa de abandono relevante foram identificados na etapa de preenchimento de dados, revelando perda de receita.', 'Although the landing page performs well and communicates clearly, the purchase flow still has significant friction points. Rage clicks and a relevant abandonment rate were identified during the data entry step, revealing revenue loss.')],
        defs: [
          { k: L('Metodologia', 'Methodology'), v: L('Análise quantitativa dos últimos 7 dias', 'Quantitative analysis of the last 7 days') },
          { k: L('Mapa de calor (Clarity)', 'Heatmap (Clarity)'), v: L('Onde os usuários clicam, rolam e desistem', 'Where users click, scroll and give up') },
          { k: L('Gravações de sessão', 'Session recordings'), v: L('Entender modelos mentais e a causa da frustração', 'Understanding mental models and the cause of frustration') },
          { k: L('Base teórica', 'Theoretical framework'), v: L('Heurísticas de Nielsen e artigos de UX — Feedback do sistema · Prevenção de erros', 'Nielsen\'s Heuristics and UX articles — System feedback · Error prevention') }
        ] },
      { t: 'split', side: 'right', img: I('mc-landing.jpg'), imgW: 640, eyebrow: L('Jornada e ponto de ruptura', 'Journey and breaking point'), title: L('Da landing à compra', 'From landing to purchase'),
        defs: [
          { k: L('A jornada (Landing → Compra)', 'The journey (Landing → Purchase)'), v: L('Os usuários, majoritariamente no desktop, exploram a landing page, buscam informações sobre funcionalidades e bancos compatíveis e seguem para o checkout com alta intenção de conversão.', 'Users, mostly on desktop, explore the landing page, look for information about features and compatible banks, and move on to checkout with high conversion intent.') },
          { k: L('O ponto de ruptura', 'The breaking point'), v: L('O atrito acontece depois da decisão de compra, concentrado no formulário de dados — é nesse momento que o engajamento cai e o abandono aumenta.', 'Friction occurs after the purchase decision, concentrated in the data form — this is the moment when engagement drops and abandonment increases.') }
        ], note: L('● Heurística de prevenção de erros', '● Error prevention heuristic') },
      { t: 'split', side: 'right', img: I('mc-heatmap.jpg'), imgW: 600, eyebrow: L('Atrito no preenchimento de dados', 'Friction in data entry'), title: L('Continuar em vez de preencher.', 'Continue instead of fill in.'),
        defs: [{ k: L('Violação de prevenção de erros (Nielsen)', 'Error Prevention Violation (Nielsen)'), v: L('Os campos obrigatórios não são claros. Os usuários preenchem em ordem aleatória e são forçados a corrigir erros evitáveis.', 'Required fields aren\'t clear. Users fill them out in random order and are forced to correct avoidable errors.') }],
        stats: [{ n: '51,93%', l: L('clicaram em "Continuar"', 'clicked "Continue"') }, { n: '3,87%', l: L('clicaram para preencher o nome', 'clicked to fill in their name') }],
        conclusion: { k: L('Conclusão', 'Conclusion'), v: L('O usuário mostra um objetivo claro: avançar. Forçar revisões e campos desnecessários vai contra o fluxo natural de compra e aumenta a taxa de abandono.', 'The user shows a clear goal: moving forward. Forcing reviews and unnecessary fields goes against the natural purchase flow and increases the abandonment rate.') } },
      { t: 'split', side: 'right', img: I('mc-form.jpg'), imgW: 600, eyebrow: L('Interface e comunicação', 'Interface and communication'), title: L('Estamos pedindo os dados na hora errada.', 'We\'re asking for the data at the wrong time.'),
        defs: [
          { k: L('O mindset do usuário', 'The user mindset'), v: L('Quem chega à tela de compra quer concluir a aquisição.', 'Whoever reaches the purchase screen wants to complete the acquisition.') },
          { k: L('O custo da interrupção', 'The cost of interruption'), v: L('Interromper o usuário no meio da tarefa principal (comprar) com demandas secundárias é uma das principais causas de abandono. O usuário está no modo compra, não no modo preencher formulário.', 'Interrupting the user in the middle of the main task (buying) with secondary demands is one of the leading causes of abandonment. The user is in buying mode, not form-filling mode.') },
          { k: L('Analogia da loja física', 'Physical store analogy'), v: L('Você decide comprar. Quando chega ao caixa, o atendente pergunta: "Nome completo? RG? CEP? Telefone?". A empolgação vai embora. No digital, o usuário simplesmente fecha a tela.', 'You decide to buy. When you get to the checkout, the cashier asks: "Full name? ID number? ZIP code? Phone number?" The excitement fades. In the digital world, the user simply closes the screen.') }
        ] },
      { t: 'split', side: 'right', img: I('mc-fields.jpg'), imgW: 520, eyebrow: L('Percepção de ação', 'Perception of action'), title: L('Onde o clique não responde', 'Where the click doesn\'t respond'),
        defs: [
          { k: L('Affordance quebrada', 'Broken affordance'), v: L('Os usuários clicam repetidamente nos rótulos ("Nome completo", "Meu celular") esperando conseguir digitar. A área clicável se limita ao campo em si, causando frustração.', 'Users repeatedly click on the labels ("Full Name", "My Phone Number") expecting to be able to type. The clickable area is limited to the input field itself, causing frustration.') },
          { k: L('Feedback do sistema', 'System feedback'), v: L('Os campos ativos não têm um destaque visual claro. O estilo atual (contorno neutro) faz o campo parecer desabilitado — o mesmo estilo usado em campos bloqueados, como o CPF.', 'Active fields lack a clear visual highlight. The current style (neutral outline) makes the field look disabled — the same style used for locked fields like the Tax ID (CPF).') },
          { k: L('Microatrito por alvo de clique incorreto', 'Micro-friction from an incorrect click target'), v: L('Na frase "Problemas com o CPF? Clique aqui", o usuário tenta clicar na frase inteira. Só "Clique aqui" é clicável, gerando dead clicks e perda de confiança.', 'In the sentence "Problems with your Tax ID (CPF)? Click here," the user tries to click on the entire sentence. Only "Click here" is clickable, resulting in dead clicks and loss of trust.') }
        ] },
      { t: 'split', eyebrow: L('Recomendações · Táticas de UX', 'Recommendations · UX tactics'), title: L('Ações imediatas para reduzir frustração e dead clicks', 'Immediate actions to reduce frustration and dead clicks'),
        defs: [
          { k: L('Aumentar a área de clique (Lei de Fitts, 1954)', 'Increase click target area (Fitts\'s Law, 1954)'), v: L('Os rótulos devem ser clicáveis e ativar o campo correspondente.', 'Labels should be clickable and activate the corresponding field.') },
          { k: L('Feedback visual imediato', 'Immediate visual feedback'), v: L('O campo ativo deve se destacar claramente (borda colorida ou sombra interna).', 'The active field should stand out clearly (colored border or inner shadow).') },
          { k: L('Ampliar a área dos links', 'Expand link click targets'), v: L('Tornar frases inteiras clicáveis ("Problemas com o CPF? Clique aqui").', 'Make entire sentences clickable ("Problems with your Tax ID (CPF)? Click here").') },
          { k: L('Otimizar o CTA ("Continuar")', 'Optimize the CTA ("Continue")'), v: L('Ajustar o texto para algo mais claro, como "Quero este plano".', 'Adjust the copy to something clearer, like "I want this plan".') }
        ], grid: true },
      { t: 'split', side: 'right', img: I('mc-attention.jpg'), imgW: 520, eyebrow: L('Recomendação estratégica', 'Strategic recommendation'), title: L('A pergunta certa, na hora certa', 'The right question, at the right time'),
        defs: [
          { k: L('Questionar o motivo de cada campo', 'Question the reason behind every field'), v: L('Revisar o formulário e remover campos não essenciais. Aplicar o conceito de Dados Mínimos Viáveis (MVD): o que é realmente necessário nesta etapa da compra?', 'Review the form and remove non-essential fields. Apply the concept of Minimum Viable Data (MVD): what\'s truly necessary at this stage of the purchase?') },
          { k: L('As perguntas certas na hora certa', 'The right questions at the right time'), v: L('Fazer as perguntas certas no momento certo — por exemplo, integrar perguntas dentro de um contexto já ativo. O Nubank aplica bem esse princípio em seus fluxos progressivos.', 'Ask the right questions at the right time — for example, integrate questions within an already active context. Nubank successfully applies this principle in its progressive flows.') }
        ], quote: L('"O momento de uma pergunta é tão importante quanto a própria pergunta." — Teresa Torres', '"The timing of a question is just as important as the question itself." — Teresa Torres') },
      { t: 'refs', eyebrow: L('Artigos de UX utilizados', 'UX articles used'), title: L('Referências', 'References'),
        items: [
          { src: 'Nielsen Norman Group', title: L('Reduzindo a carga cognitiva em sistemas complexos', 'Minimize Cognitive Load to Maximize Usability'), href: 'https://www.nngroup.com/articles/minimize-cognitive-load/' },
          { src: 'Nielsen Norman Group', title: L('A Lei de Fitts e suas aplicações em UX', 'Fitts\'s Law and Its Applications in UX'), href: 'https://www.nngroup.com/articles/fitts-law/' },
          { src: 'Nielsen Norman Group', title: L('10 Heurísticas de Nielsen para o Design de Interface', '10 Usability Heuristics for User Interface Design') }
        ] }
    ]
  }
};
